#!/usr/bin/env python3
"""Emit every results table used by the report, straight from the artefacts.

Hand-copied numbers drift.  FINDINGS.md quotes the tables this script writes to
``automl/reports/tables.md``, so a refresh regenerates them from the JSONL and
parquet outputs rather than from memory.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd

from automl.experiment import load_results

REPO = Path(__file__).resolve().parents[1]
SWEEPS = REPO / "automl/artifacts/sweeps"
OUT = REPO / "automl/reports/tables.md"

HEAD = ["r2_overall", "r2_between", "r2_within", "r2_within_composition",
        "sel_spearman_mean", "sel_logSF_r2", "mae"]
NICE = {"r2_overall": "R² overall", "r2_between": "R² between",
        "r2_within": "R² within", "r2_within_composition": "R² within-comp",
        "sel_spearman_mean": "series Spearman", "sel_logSF_r2": "log-SF R²",
        "mae": "MAE", "n_features": "n feat", "preset": "preset",
        "model": "model", "weight_scheme": "weights", "config": "configuration"}

PRESET_LABEL = {
    "baseline_2d": "2D baseline", "plus_g1": "+G1 first shell",
    "plus_g2": "+G2 contraction", "plus_g3": "+G3 polyhedron",
    "plus_g4": "+G4 steric", "plus_g5": "+G5 xTB electronics",
    "plus_g6": "+G6 metal RDF", "plus_g7": "+G7 global shape",
    "plus_g8": "+G8 chelate", "plus_g9": "+G9 topology",
    "plus_g10": "+G10 series-relative", "plus_g11": "+G11 persistence images",
    "plus_g12c": "+G12c denoised values", "plus_g13c": "+G13c family slopes",
    "plus_g14c": "+G14c family means (metal-free)",
    "plus_g15c": "+G15c CN-effect removed",
    "plus_p3d_phys": "+shipped physical", "plus_p3d_poly": "+shipped polyhedron",
    "plus_p3d_all": "+shipped 3D (both)", "inner_sphere": "+inner sphere G1+G2+G3+G8",
    "ligand3d_only": "+metal-free 3D only", "denoised": "+denoised set",
    "cnfree_ligand": "+CN-free & metal-free", "g5_ligand": "+G5 & metal-free",
    "core3d_qc": "+curated g_core", "all_3d": "+all 3D (dilution control)",
}


def _md(df: pd.DataFrame, cols: list[str], nd: int = 4) -> str:
    cols = [c for c in cols if c in df.columns]
    v = df[cols].copy()
    for c in cols:
        if pd.api.types.is_numeric_dtype(v[c]):
            v[c] = v[c].map(lambda x: "" if pd.isna(x) else f"{x:.{nd}f}")
    v = v.rename(columns={c: NICE.get(c, c) for c in cols})
    return v.to_markdown(index=False)


def _delta_table(d: pd.DataFrame, ref_preset: str) -> pd.DataFrame:
    if ref_preset not in set(d["preset"]):
        return d
    b = d[d["preset"] == ref_preset].iloc[0]
    out = d.copy()
    for m in ("r2_overall", "r2_within", "sel_logSF_r2", "sel_spearman_mean"):
        if m in out.columns:
            out[f"Δ{NICE.get(m, m)}"] = out[m] - b[m]
    return out


def main() -> int:
    lines: list[str] = ["# Generated results tables", "",
                        "_Regenerated by `python3 -m automl.make_tables`; "
                        "do not hand-edit._", ""]
    A = lines.append

    # --- CatBoost ablation, protocol B --------------------------------------
    cb = load_results(SWEEPS / "ablation_catboost")
    if len(cb):
        cb = cb.sort_values("r2_overall", ascending=False)
        cb["label"] = cb["preset"].map(lambda p: PRESET_LABEL.get(p, p))
        cb = _delta_table(cb, "baseline_2d")
        A("## CatBoost + inverse-extractant weights, 3D block ablation "
          "(protocol B, 5×3)")
        A("")
        A(_md(cb, ["label", "n_features"] + HEAD +
              ["ΔR² overall", "ΔR² within", "Δlog-SF R²"]))
        A("")

    # --- LightGBM ablation, protocol A --------------------------------------
    lg = load_results(SWEEPS / "ablation")
    if len(lg):
        lg = lg[(lg["row_filter"] == "has3d") & (lg["model"] == "lgbm")]
        lg = lg.sort_values("r2_overall", ascending=False)
        lg["label"] = lg["preset"].map(lambda p: PRESET_LABEL.get(p, p))
        lg = _delta_table(lg, "baseline_2d")
        A("## LightGBM 3D block ablation (protocol A, screening only)")
        A("")
        A(_md(lg, ["label", "n_features"] + HEAD +
              ["ΔR² overall", "ΔR² within", "Δlog-SF R²"]))
        A("")

    # --- model family -------------------------------------------------------
    md = load_results(SWEEPS / "models")
    if len(md):
        for preset in sorted(md["preset"].unique()):
            sub = md[md["preset"] == preset].sort_values("r2_overall", ascending=False)
            A(f"## Model family × sample weighting — preset `{preset}` (protocol A)")
            A("")
            A(_md(sub, ["model", "weight_scheme"] + HEAD))
            A("")

    # --- robust target ------------------------------------------------------
    rb = load_results(SWEEPS / "robust")
    if len(rb):
        rb = rb.sort_values("r2_overall", ascending=False)
        rb["objective"] = rb["params_json"].map(
            lambda s: json.loads(s).get("objective", "l2"))
        rb["clip"] = rb.get("target_clip", 0.0)
        A("## Robust-target and weighting variants (protocol B)")
        A("")
        A(_md(rb, ["preset", "model", "clip", "objective", "weight_scheme"] + HEAD))
        A("")

    # --- combination test ---------------------------------------------------
    cm = load_results(SWEEPS / "combo")
    if len(cm):
        cm = cm.sort_values("r2_overall", ascending=False)
        cm["label"] = cm["preset"].map(lambda p: PRESET_LABEL.get(p, p))
        A("## Complementary-block combinations (protocol B)")
        A("")
        A(_md(cm, ["label", "model", "n_features"] + HEAD))
        A("")

    # --- single-CN subset test ---------------------------------------------
    sc = load_results(SWEEPS / "singlecn")
    if len(sc):
        sc["label"] = sc["preset"].map(lambda p: PRESET_LABEL.get(p, p))
        A("## Single-CN subset test (protocol B, CatBoost + group_inv)")
        A("")
        A("Inside either subset the CN-9/CN-8 staircase does not exist. "
          "`cn9_light` = La-Gd (3980 rows, 187 extractants), "
          "`cn8_heavy` = Tb-Lu (1966 rows, 82 extractants), "
          "`has3d` = the full series (5946 rows).")
        A("")
        for rf in ("has3d", "cn9_light", "cn8_heavy"):
            sub = sc[sc["row_filter"] == rf]
            if sub.empty:
                continue
            sub = sub.sort_values("r2_overall", ascending=False)
            base = sub[sub["preset"] == "baseline_2d"]
            if len(base):
                sub = sub.copy()
                sub["ΔR² overall"] = sub["r2_overall"] - base.iloc[0]["r2_overall"]
            A(f"### rows = `{rf}`")
            A("")
            A(_md(sub, ["label", "n_features"] + HEAD + ["ΔR² overall"]))
            A("")

    # --- matched-coverage test ----------------------------------------------
    mt = load_results(SWEEPS / "matched")
    if len(mt):
        mt["label"] = mt["preset"].map(lambda p: PRESET_LABEL.get(p, p))
        A("## Matched-coverage test: is the heavy-half 3D benefit chemistry or "
          "data thinness?")
        A("")
        A("`cn9_matched:N` = La-Gd subsampled to the Tb-Lu coverage profile "
          "(82 extractants, 20 with >=10 rows, matched size distribution), "
          "three independent draws. `cn8_heavy` is the control.")
        A("")
        for rf in sorted(mt["row_filter"].unique()):
            sub = mt[mt["row_filter"] == rf].sort_values("r2_overall", ascending=False)
            base = sub[sub["preset"] == "baseline_2d"]
            if len(base):
                sub = sub.copy()
                sub["ΔR² overall"] = sub["r2_overall"] - base.iloc[0]["r2_overall"]
            A(f"### rows = `{rf}`")
            A("")
            A(_md(sub, ["label"] + HEAD + ["ΔR² overall"]))
            A("")

    # --- champion + paired deltas ------------------------------------------
    pc = REPO / "automl/reports/paired_comparison.csv"
    if pc.exists():
        t = pd.read_csv(pc).sort_values("r2_overall", ascending=False)
        A("## Champion configurations, 5 repeats × 5 folds (protocol B)")
        A("")
        A(_md(t, ["config"] + HEAD))
        A("")
        if "d_r2_overall" in t.columns:
            A("### Paired bootstrap vs the LightGBM baseline "
              "(400 cluster draws over extractants)")
            A("")
            v = t.dropna(subset=["d_r2_overall"]).copy()
            v["ΔR²"] = v["d_r2_overall"]
            v["90% lo"] = v["d_r2_overall_lo"]
            v["90% hi"] = v["d_r2_overall_hi"]
            v["P(better)"] = v["d_r2_overall_p_better"]
            v["ΔR² within"] = v["d_r2_within"]
            v["P(within better)"] = v["d_r2_within_p_better"]
            A(_md(v, ["config", "ΔR²", "90% lo", "90% hi", "P(better)",
                      "ΔR² within", "P(within better)"], nd=4))
            A("")

    # --- ensemble -----------------------------------------------------------
    ens = REPO / "automl/reports/ensemble_results.csv"
    if ens.exists():
        A("## Stacked ensemble (protocol B out-of-fold predictions only)")
        A("")
        A(_md(pd.read_csv(ens), ["combiner"] + HEAD))
        A("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({len(lines)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
