#!/usr/bin/env python3
"""Every headline number in a report must appear in the CSV it came from.

Why this exists
---------------
This study's worst bug was a figure and a table computing the same quantity two
different ways, and its most persistent one is prose drifting from its own
data. `PI_SWEEP_RESULTS.md`'s summary block still asserted a "+0.064 gap" that
its own §9 had withdrawn; `SYNTHESIS.md` repeated it. Nobody noticed for a week,
because nothing checked.

So: for each claim below, read the number out of the result CSV and assert the
string appears in every document that quotes it. It cannot catch a wrong number
that is quoted consistently, but it catches the failure mode this project
actually has -- a corrected table and an uncorrected paragraph.

Skips cleanly when the CSVs are absent, so a fresh checkout without the
artifacts still passes.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd
import pytest

REPORTS = Path(__file__).resolve().parents[1] / "reports"

# (label, csv, pandas query, column, documents that quote it)
CLAIMS = [
    ("dual-key drop-in, binned", "dualkey_test.csv",
     "key=='composition_key' and base=='no topology (CatBoost+repaired)'",
     "delta",
     ["DUALKEY_RESULTS.md", "REANALYSIS_2026-07-29.md", "SYNTHESIS.md",
      "README.md"]),
    ("dual-key drop-in, strict", "dualkey_test.csv",
     "key=='strict_composition_key' and base=='no topology (CatBoost+repaired)'",
     "delta",
     ["DUALKEY_RESULTS.md", "REANALYSIS_2026-07-29.md"]),
    ("encoder decisive contrast", "encoder_test.csv",
     "key=='composition_key' and base=='with D0'", "delta",
     ["ENCODER_RESULTS.md", "REANALYSIS_2026-07-29.md", "SYNTHESIS.md"]),
    ("full stack over all arms", "full_stack.csv",
     "key=='composition_key'", "adj_r2",
     ["REANALYSIS_2026-07-29.md"]),
]


def _forms(v: float) -> list[str]:
    """Renderings a report might legitimately use for one number."""
    return [f"{v:+.4f}", f"{v:.4f}", f"{abs(v):.4f}", f"{v:+.3f}", f"{v:.3f}"]


@pytest.mark.parametrize("label,csv,query,col,docs", CLAIMS,
                         ids=[c[0] for c in CLAIMS])
def test_reports_quote_their_own_csv(label, csv, query, col, docs):
    path = REPORTS / csv
    if not path.exists():
        pytest.skip(f"{csv} not present (artifacts not built)")
    frame = pd.read_csv(path).query(query)
    if frame.empty:
        pytest.skip(f"{csv} has no row matching {query!r}")
    value = float(frame[col].iloc[0])
    forms = _forms(value)
    for doc in docs:
        p = REPORTS / doc
        if not p.exists():
            pytest.skip(f"{doc} not present")
        text = p.read_text()
        assert any(f in text for f in forms), (
            f"{doc} quotes no rendering of {label} = {value:+.4f} "
            f"(tried {forms}); the document has drifted from {csv}")


def test_ceiling_is_a_ceiling():
    """A 'ceiling' outside (0, 1] is not a ceiling, and must be marked invalid."""
    path = REPORTS / "ceiling_test.csv"
    if not path.exists():
        pytest.skip("ceiling_test.csv not present")
    d = pd.read_csv(path)
    assert "valid" in d.columns, "ceiling_test.csv must carry a validity column"
    good = d[d["valid"]]
    assert len(good), "no estimator produced a usable ceiling"
    assert (good["ceiling_r2"] > 0).all() and (good["ceiling_r2"] <= 1).all()
    # and the ones marked invalid really are outside the range
    bad = d[~d["valid"]]
    assert ((bad["ceiling_r2"] <= 0) | (bad["ceiling_r2"] > 1)).all()


def test_published_headline_still_matches_stack_test():
    """The three published contrasts must not move.

    stack_test.csv is regenerated by several commands.  It was once overwritten
    at n_boot=100 by a verification job, which silently degraded it; this pins
    both the values and the draw count.
    """
    path = REPORTS / "stack_test.csv"
    if not path.exists():
        pytest.skip("stack_test.csv not present")
    d = pd.read_csv(path).set_index("contrast")
    assert (d["n_boot"] == 400).all(), (
        "stack_test.csv was written with the wrong number of bootstrap draws; "
        "re-run `python3 -m automl.topo.stack_test --n-boot 400`")
    assert d.loc["1_primary", "delta"] == pytest.approx(0.0351, abs=5e-4)
    assert d.loc["3_decisive", "delta"] == pytest.approx(0.0296, abs=5e-4)
